[package]
name = "seedelf-koios"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4.3"
reqwest = { version = "0.12.9", features = ["json"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
# seedelf stuff
seedelf-crypto = { path = "../seedelf-crypto" }